# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '计算出每个cell的高度' do

end

target '计算出每个cell的高度Tests' do

end

target '计算出每个cell的高度UITests' do

end

