# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZFB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZFB


pod 'Masonry', '1.0.1'
pod 'MBProgressHUD', '1.0.0'

  target 'ZFBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZFBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
