# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDWebImageTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SDWebImageTest

  pod 'SDWebImage', '3.8.2'

  target 'SDWebImageTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDWebImageTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
