# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'snapkitTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for snapkitTest
  pod 'SnapKit'
  pod 'Alamofire', '~> 4.0.1'

 target 'snapkitTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'snapkitTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
